### ISSUE TITLE
Following the "Viewing Docs Locally" instructions gives me an error on npm run update

### ISSUE THREAD

**Issue by hugozap** [datproject/docs#51]
Steps 1,2 and 3 succeed but I get the following on step 4
(Do I have to run some ecosystem-docs command first? )

> dat-docs@1.0.0 update:build /Users/hugo/LearningSpace/dat/docs
> cat repos.txt | ecosystem-docs sync && cat repos.txt | ecosystem-docs read | node scripts/build.js

Your GitHub username: datproject/dat
Your GitHub password: ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔

/Users/hugo/LearningSpace/dat/docs/node_modules/ecosystem-docs/bin.js:81
  if (err) throw err
           ^

Error: Bad credentials
    at BufferList.afterCreateAuthResponse [as _callback] (/Users/hugo/LearningSpace/dat/docs/node_modules/ghauth/ghauth.js:40:19)
    at BufferList.end (/Users/hugo/LearningSpace/dat/docs/node_modules/ghauth/node_modules/bl/bl.js:98:10)
    at DuplexWrapper.onend (/Users/hugo/LearningSpace/dat/docs/node_modules/hyperquest/node_modules/readable-stream/lib/_stream_readable.js:537:10)

**Comment by joehand** [comment]
@hugozap sorry still a bit YOLO with the ecosystems docs stuff. 

Yes, I *think* this should be solved by making sure you can run & are logged in already with `ecosystem-docs*:

Install and login:

```sh
npm install -g ecosystem-docs
ecosystem-docs 
# will make you login
```

See if you can read a repo:

```sh
echo 'datproject/dat' | ecosystem-docs sync
```

If that works, then you should be able to do the build for our docs.
